name: Game-compatibility Bug Report
description: Report an issue experienced with a particular game
title: "[Game]: Game name - short description of bug"
labels: ["game-specific", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug for a specific game? Please fill out the sections below.
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you report this bug, please consider the following.
      options:
        - label: This issue doesn't already exists
        - label: This bug is only related to a single game
        - label: Filled out the title with template
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: | 
        A summary of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better instructions are, the easier it will be to resolve.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: Technical details
      description: |
        - Game version number:
        - Anything else?
  - type: input
    id: version
    attributes:
      label: version
      description: Which version of Borderless Gaming were you using? Visible in Help->About-menu.
      placeholder: ex. 9.5.6.1328 or N/A
    validations:
      required: true