name: Bug Report
description: Report a general issue encountered Borderless-Gaming
title: Short description of the bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug? Please fill out the sections below.
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you report this bug, please consider the following.
      options:
        - label: This issue doesn't already exist
        - label: This bug is Not related to compatability with a specific game
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A summary of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better instructions are, the easier it will be to resolve.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: Technical details
      description: |
        - Any way you can elaborate?
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: version
      description: Which version of Borderless Gaming were you using? Visible in Help->About-menu.
      placeholder: ex. 9.5.6.1328 or N/A
    validations:
      required: true